refactor code
kamilinw/mailbox pull request #1
Opened 2021-05-04 15:47 UTC by kamilinw

2021-05-04 19:09 UTC, konradstach requested changes
test

2021-05-04 19:09 UTC, konradstach commented on src/main/java/pl/kamilwnek/mailbox/controller/MailboxController.java
> +    @PatchMapping(value = "/{whichMailbox}")
whichMailbox zamieniłbym jednak na mailboxId, bo to jednoznacznie określa, które pole jest identyfikatorem encji

2021-05-04 19:15 UTC, konradstach commented on .gitignore
> +*.iws
test

2021-05-05 17:38 UTC, konradstach requested changes

2021-05-05 17:38 UTC, konradstach commented on src/main/java/pl/kamilwnek/mailbox/model/Mailbox.java
> +    )
dla prostych zastosowań wystarczyłoby tylko @GeneratedValue(strategy = GenerationType.SEQUENCE), ale jak najbardziej można korzystać z sekwencji bazodanowych
https://stackoverflow.com/questions/2595124/how-does-the-jpa-sequencegenerator-annotation-work

2021-05-05 17:38 UTC, konradstach commented on src/main/java/pl/kamilwnek/mailbox/model/Mailbox.java
> +    private List<LocalDateTime> mailHistory;
Tu nie wiem o co chodzi, w jaki sposób jest przetrzymywana historia maili, gdy przetrzymujesz tylko LocalDateTime?

2021-05-05 17:38 UTC, konradstach commented on src/main/java/pl/kamilwnek/mailbox/model/Mailbox.java
> +    private Long mailboxId;
id encji powinny być raczej nazywane id
i tak bedzie wiadomo, że dotyczy to mailboxa, bo pole jest prywatne więc dostęp do niego i tak będzie przez mailbox.get/setId()

2021-05-05 17:38 UTC, konradstach commented on src/main/java/pl/kamilwnek/mailbox/service/EmailService.java
> +    private static final Logger LOGGER = LoggerFactory.getLogger(EmailService.class);
To też można załatwić lombokiem @Log tworzy takie pole automatycznie

2021-05-05 17:38 UTC, konradstach commented on src/main/java/pl/kamilwnek/mailbox/service/MailboxService.java
> +        var mailbox = mailboxRepository.findById(id).orElse(null);
Nie używam tych nowych wersji javy, także nie wiem jak odbiera się var
Poszukaj sobie i doczytaj sam, czy nie jest lepiej odbierane mocne typowanie na konkretny typ

2021-05-05 17:38 UTC, konradstach commented on src/main/java/pl/kamilwnek/mailbox/service/MailboxService.java
> +            mailbox.setMailHistory(history);
To do przetestowania, ale chyba mógłbyś zastąpić te 3 linijki jedną: mailbox.getMailHistory().add(LocalDateTime.now())
mailbox.getMailHistory() nie potrzebuje zmiany referencji (czyli tworzenia nowego obiektu listy i dokładania nowego elementu) tylko dołożenia nowego elementu do istaniejącej listy

2021-05-05 17:38 UTC, konradstach commented on src/main/java/pl/kamilwnek/mailbox/service/MailboxService.java
> +        mailboxRepository.save(mailbox);
to też do przetestowania, ale chyba save nie jest konieczny, hibernate tym swoim dirty-checking powinien sobie sam ogarnąć update

2021-05-05 17:38 UTC, konradstach commented on src/main/java/pl/kamilwnek/mailbox/service/RegistrationService.java
> +        System.out.println("in RegistrationService.register(). sent link:" + link + " to " + request.getEmail());
Jak już używasz loggera to niech wszystkie logi będą tam a nic nie wypisuje się w konsoli

2021-05-05 17:38 UTC, konradstach commented on src/main/java/pl/kamilwnek/mailbox/service/RegistrationService.java
> +}
Kurde trzymanie takiej templatki w kodzie za ładne nie jest
Fajnie by ją było przenieść do jakiegoś zewnętrznego pliku i zaczytać w tym momencie, ale trzeba jeszcze wstrzyknąć do niej name i link
Można ewentualnie zrobić tak, że tworzysz templatke i w niej tam gdzie ma być name i link wstawiasz np "#NAME" i "#LINK". Póżniej zaczytujesz ją do zmiennej 'template' i możesz robić na niej coś takiego:
`template = template.replaceFirst(#NAME, name");`
`template = template.replaceFirst(#LINK, link");`

2021-05-05 17:38 UTC, konradstach commented on src/main/java/pl/kamilwnek/mailbox/service/UserService.java
> +            e.printStackTrace();
Wrzuć coś do logów, staraj się nie zostawiać tylko stack trace w catchu

2021-05-05 17:38 UTC, konradstach commented on src/test/java/pl/kamilwnek/mailbox/MailBoxApiApplicationTests.java
> +class MailBoxApiApplicationTests {
Dopisanie jakiś testów nie byłoby złe. Jak chcesz to zobacz sobie jakieś przykłady. Biblioteki jUnit i Mockito w zupełności wystarczą

2021-05-05 21:16 UTC, kamilinw commented on src/main/java/pl/kamilwnek/mailbox/controller/MailboxController.java
> +    @PatchMapping(value = "/{whichMailbox}")
Właśnie tutaj mam takie założenie że program w urządzeniu zna tylko nazwę użytkownika i hasło do użytkownika o roli MAILBOX. Więc skrzynka nie wie jakie ma id w bazie danych. Więc jak skrzynka wysyła dane na serwer to serwer musi ogarnąć jakie id skrzynki jest przypisane do użytkownika który dokonuje zmian. (W założeniu użytkownik MAILBOX posiada tylko jedną skrzynkę)
Użytkownik o roli USER, który powiedzmy kupi skrzynkę dopiero dodaje do bazy danych użytkownika MAILBOX (poprzez wpisanie użytkownika i hasła podanego dajmy na to na pudełku) razem z dodaniem nowej skrzynki do bazy danych.

2021-05-05 21:19 UTC, kamilinw commented on src/main/java/pl/kamilwnek/mailbox/controller/MailboxController.java
> +    public Mailbox getFirstMailbox(@RequestHeader(HttpHeaders.AUTHORIZATION) String authorizationHeader){
To w przypadku gdyby skrzynka chciała odczytać jakie dane są zapisane w serwerze. First odnosi się do pierwszej skrzynki zalogowanego użytkownika

2021-05-05 21:22 UTC, kamilinw commented on src/main/java/pl/kamilwnek/mailbox/controller/MailboxController.java
> +    @GetMapping("/temperature/{id}")
Tak id to id mailboxa. To faktycznie muszę zmienić

2021-05-05 21:23 UTC, kamilinw commented on src/main/java/pl/kamilwnek/mailbox/controller/MailboxController.java
> +}
Właśnie myślałem o tym ale nie wiem czy się wyrobię ze wszystkim bo jeszcze websocketów nie robiłem na androidzie a to może chwilę zejść zanim poszukam jak się to robi

2021-05-05 21:30 UTC, kamilinw commented on src/main/java/pl/kamilwnek/mailbox/controller/UserController.java
> +                             @RequestParam(value = "whichMailbox", required = false, defaultValue = "0") int whichMailbox){
Wiem ale whichMailbox to nie jest Id skrzynki w bazie danych tylko liczba porządkowa skrzynki jakie posiada użytkownik. Zakładam że jeden użytkownik nie będzie miał tyle skrzynek żeby się w int-cie nie zmieściło. Zwracane jest id skrzynki użytkownika, które już jest longiem

2021-05-05 21:31 UTC, kamilinw commented on src/main/java/pl/kamilwnek/mailbox/model/Mailbox.java
> +    )
Dawałem na początku chyba AUTO to mi co 50 przydzielało więc zrobiłem tak

2021-05-05 21:32 UTC, kamilinw commented on src/main/java/pl/kamilwnek/mailbox/model/Mailbox.java
> +    private List<LocalDateTime> mailHistory;
Historia w takim sensie że lista dat w których został dostarczony list

2021-05-05 21:39 UTC, kamilinw commented on src/main/java/pl/kamilwnek/mailbox/service/MailboxService.java
> +        var mailbox = mailboxRepository.findById(id).orElse(null);
tak mi zasugerował Sonar lint. Tutaj to var po prostu znaczy to samo co Mailbox. Skoro się inicjuje zmienną przypisując typ Mailbox to ta zainicjowana zmienna musi być tego samego typu.

2021-05-05 21:41 UTC, kamilinw commented on src/main/java/pl/kamilwnek/mailbox/service/MailboxService.java
> +        mailboxRepository.save(mailbox);
No możliwe. W niektórych miejscach nie działało dlatego w większości przypadków daję :D

2021-05-05 21:42 UTC, kamilinw commented on src/main/java/pl/kamilwnek/mailbox/service/RegistrationService.java
> +        System.out.println("in RegistrationService.register(). sent link:" + link + " to " + request.getEmail());
Zapomniałem usunąć :D

2021-05-05 21:43 UTC, kamilinw commented on src/main/java/pl/kamilwnek/mailbox/service/RegistrationService.java
> +}
Wiem że to brzydko wyglądało ale właśnie nie miałem za bardzo pomysłu jak to na szybko ugryźć. Spróbuję tak jak piszesz

2021-05-05 21:44 UTC, kamilinw commented on src/test/java/pl/kamilwnek/mailbox/MailBoxApiApplicationTests.java
> +class MailBoxApiApplicationTests {
No pomyślę ale nie wiem czy najpierw nie zrobię appki na androida bo to pewnie też chwilę zejdzie

2021-05-05 21:46 UTC, kamilinw commented on src/main/java/pl/kamilwnek/mailbox/config/VerificationTokenConfig.java
> +    }
No dodam lomboka bo faktycznie to jednak dużo daje

2021-05-05 21:49 UTC, kamilinw commented on src/main/java/pl/kamilwnek/mailbox/model/Mailbox.java
> +    private Long mailboxId;
No racja ale to chyba tragedii chyba nie ma jak na razie zostanie a będę wiedział na przyszłość? :D

2021-05-06 11:07 UTC, kamilinw commented on src/main/java/pl/kamilwnek/mailbox/service/MailboxService.java
> +        mailboxRepository.save(mailbox);
Bez tego nie działa

2021-05-11 19:55 UTC, konradstach commented on src/main/java/pl/kamilwnek/mailbox/model/Mailbox.java
> +    private List<LocalDateTime> mailHistory;
To może warto to nazwać jakoś inaczej, może coś bardziej w stylu mailsDeliveryDates, żeby nie sugerować, że pod mailHistory kryje się cała historia maili w skrzynce

2021-05-11 19:58 UTC, konradstach commented on src/main/java/pl/kamilwnek/mailbox/service/MailboxService.java
> +        mailboxRepository.save(mailbox);
to pewnie już bedzie kwestia konfiguracji samego hibernate
ale z savem moim zdaniem czytelniej jest i tak

2021-05-17 08:03 UTC, merged